### ISSUE TITLE
Add appbar in events screen

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#10]
### Explanation in detail
- Create an appbar according to the UI attached.
- Take mlsa-logo.png from https://drive.google.com/file/d/1Zlnne3-B7KuVtB_9mxFQuhwCSXcohnzk/view?usp=sharing
- Put the image in assets/images/ directory.

#### Color
- Background gradient color should be on the whole screen.
- Appbar color is transparent.

#### Color Codes for gradient
#219653
#792ADC

#### UI Attached
![Frame 1](https://user-images.githubusercontent.com/56784565/134962079-08eb5fd2-b6d4-4c64-bb1e-60b37cf720e7.png)

**Comment by AgungPrabowo** [comment]
I would like to take this.

**Comment by pranshi112** [comment]
Read the contribution guidelines and go ahead.
