### ISSUE TITLE
Event page UI

### ISSUE THREAD

**Issue by vidita-bit** [mlsa-amu/MLSA-AMU#11]
#### Explanation in detail
- Create UI according to the screenshot attached.
- Take assets from https://drive.google.com/drive/folders/12xsLP-FgAKwrZsh14FlqdEfChXoyBxz9?usp=sharing
- Put assets in `assets/images/` directory.

#### UI attached
![EventScreen](https://user-images.githubusercontent.com/56840285/134969683-cce8d327-a826-486a-9096-376044be6858.png)

**Comment by AgungPrabowo** [comment]
I would like to take this.

**Comment by vidita-bit** [comment]
Sure
