### ISSUE TITLE
Team Screen UI

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#12]
#### Explanation in detail
- Create UI according to the screenshot attached.
- Github and Linkedin are icons buttons, not images.

#### UI attached
![Frame 7](https://user-images.githubusercontent.com/56784565/134971150-2cbe1bdc-ec5b-4bcb-bfb3-97d684d0d95f.png)

**Comment by Shash0501** [comment]
Hey, @harshtaliwal30, I would like to work on this issue.

**Comment by harshtaliwal30** [comment]
Read contributing guidelines and start working on the issue.

**Comment by Shash0501** [comment]
Should I use Dummy Data for the UI or make the UI with real ones ?

**Comment by harshtaliwal30** [comment]
You can use dummy data but the code should be dynamic.

**Comment by Shash0501** [comment]
@harshtaliwal30 
I have made the Team UI screen as per your need.

> The GitHub and LinkedIn icons on press open the respective sites in the browser as of now.

**Do you want me to make any other changes?**
### UI
![image](https://user-images.githubusercontent.com/75673036/135624699-5b3e3a63-872b-4db5-9970-71c320f1214d.png)
