### ISSUE TITLE
Enhancement in events screen app bar

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#15]
#### Explain in detail
- Use the AppBar widget instead of the row widget which means replace all static code with dynamic including using media queries.
- Appbar background should be transparent and the gradient should apply to the whole screen.

**Comment by pri1311** [comment]
Hie. I can take up this issue.

**Comment by harshtaliwal30** [comment]
Read the contributing guidelines and start working on this issue.
