### ISSUE TITLE
Add Appbar in Team Screen

### ISSUE THREAD

**Issue by vidita-bit** [mlsa-amu/MLSA-AMU#17]
### Explanation
- Add appbar in teams screen(`team_screen.dart`) with transparent background.
- Text should be "**Team**" with white color.
- Text in app bar should be left aligned .
- Include back button in appbar (white color).

**Comment by Shash0501** [comment]
@vidita-bit  Ma'am, I would like to take up this issue.

**Comment by vidita-bit** [comment]
Sure, assigning it to you.

**Comment by Shash0501** [comment]
@vidita-bit Ma'am, this is how I made changes to the AppBar

![image](https://user-images.githubusercontent.com/75673036/135670082-37a1c298-afb1-49de-b5c6-3cc846ca9f23.png)

If it matches your expectations, I can create a PR or please suggest the required changes.

**Comment by Shash0501** [comment]
@vidita-bit Ma'am
I have experience using **HIVE** and **Firebase** and implementing **State Management** using **Bloc**.
So I would be grateful if you could create more issues and assign them to me.
I would be glad to contribute to this project.

**Comment by vidita-bit** [comment]
@Shash0501 Nice to see your interest towards flutter . We would be creating some more screens issue tonight , you can work on them from tomorrow.
