### ISSUE TITLE
Contributors screen UI

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#22]
#### Explanation
- Create UI according to the screenshot attached in the file `contributors_screen.dart`.
- Use the same background color gradient as used in `team_screen.dart`.

#### UI Attached
![Frame 2](https://user-images.githubusercontent.com/56784565/135724310-b21674df-47c3-4743-9cb8-79386a92dc67.png)

**Comment by Mastersam07** [comment]
Please assign this to me

**Comment by harshtaliwal30** [comment]
Okay, I am assigning this issue to you

**Comment by Mastersam07** [comment]
I am currently on this @javeriatabassum145

**Comment by harshtaliwal30** [comment]
@Mastersam07 you can continue your work on this issue.
@javeriatabassum145 we will be opening new issues probably by tonight you can take from them.

**Comment by javeriatabassum145** [comment]
Ok @Mastersam07.
@harshtaliwal30 Sure Thanks.

**Comment by harshtaliwal30** [comment]
what is the update @Mastersam07 ?

**Comment by Mastersam07** [comment]
Sending a pr for this shortly @harshtaliwal30

**Comment by Mastersam07** [comment]
Sent a PR for this @harshtaliwal30

**Comment by Mastersam07** [comment]
Sent a fresh PR for this in #35
