### ISSUE TITLE
Replace network image

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#4]
## Details
- Take `mlsa-logo.png` from https://drive.google.com/file/d/1Zlnne3-B7KuVtB_9mxFQuhwCSXcohnzk/view?usp=sharing
- Put the image in `assets/images/` directory.
- Replace the network image with the asset image in `spash_screen.dart`

**Comment by DireWolf707** [comment]
Hye, I am new to open source and want to contribute to this issue for hacktoberfest.
So, can you assign this issue to me?

**Comment by harshtaliwal30** [comment]
Sure, start working on this issue and read the contributing guidelines.

**Comment by Takane42** [comment]
hi, is this issue already solved? if not, can you assign this issue to me?

**Comment by harshtaliwal30** [comment]
@DireWolf707 are you working on this issue?

**Comment by DireWolf707** [comment]
Sry, I appologize for not informing I was unable to solve this issue.
You can assign it to the other person.

**Comment by sarthakvaishnav09** [comment]
Hey @harshtaliwal30, I would like to work on this.

**Comment by harshtaliwal30** [comment]
Okay @DireWolf707 no issues,  if I could help you in any way then let me know.

**Comment by harshtaliwal30** [comment]
@Takane42 should I assign this issue to you?

**Comment by Takane42** [comment]
on my way doing it
