### ISSUE TITLE
Add date card in events screen

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#41]
#### Explanation in detail
 - Add a date card at the top right corner of each event card according to the UI attached.
#### UI attached
![Frame 3](https://user-images.githubusercontent.com/56784565/137783295-cee67ca3-28d9-4fd2-9f9d-53209ad5e81c.png)

**Comment by pri1311** [comment]
Can I take up this issue?

**Comment by harshtaliwal30** [comment]
Yes, you can work on this issue.
