### ISSUE TITLE
Add about section in event details screen

### ISSUE THREAD

**Issue by harshtaliwal30** [mlsa-amu/MLSA-AMU#42]
#### Explanation in detail
 - Add about section below winners.
 - Follow attached UI.
#### UI attached
![Frame 9](https://user-images.githubusercontent.com/56784565/137786026-930f4a66-6d81-4be6-891e-17cf9dcced29.png)

**Comment by Adarsh879** [comment]
I have submitted my PR , please do review it and let met know if any changes required.

**Comment by harshtaliwal30** [comment]
Before submitting the PR, make sure the issue is assigned to you.
For now, I am assigning this to you. Do remember next time.
