### ISSUE TITLE
Contact Us Screen

### ISSUE THREAD

**Issue by vidita-bit** [mlsa-amu/MLSA-AMU#43]
#### Explain in detail
- Create UI of the contact us screen as given in screen shot attached.
- File name should be `contact_screen.dart`.
- Color gradients should be same as used in other project files.
- Social media icons should have url launcher implementation

![Frame 10](https://user-images.githubusercontent.com/56840285/137786495-5d32adc3-6760-4745-b091-d6280e802dc0.png)
.

**Comment by Pakeetharan** [comment]
Can you assign me this? @vidita-bit

**Comment by vidita-bit** [comment]
> Can you assign me this? @vidita-bit

Sure
